Repository tiarasjec/website, pull requests merged in 2024-04, with the labels that each got.

#14 feat(Loading) : loading page
  src/app/loading.tsx
Labels: priority: low

#13 feat(navbar): Floating navbar
  src/app/layout.tsx
  src/components/shared/preline.tsx
  src/components/ui/hover/button.tsx
  src/components/widgets/Header.tsx
  src/components/widgets/Hero.tsx
Labels: priortiy: medium

#19 feat(navbar): hide while scrolling down
  src/components/widgets/Header.tsx
Labels: priortiy: medium

#15 Events Page
  package-lock.json
  package.json
  public/Categories/Mega.jpg
  src/app/(content)/events/[category]/event/[id]/page.tsx
  src/app/(content)/events/[category]/page.tsx
  src/app/(content)/events/page.tsx
  src/app/api/events/[category]/event/[id]/route.ts
  src/app/api/events/[category]/route.ts
  src/app/api/events/route.ts
  src/app/api/gallery/route.ts
  src/components/ui/CategoryCard.tsx
  src/components/ui/EventCard.tsx
  src/components/ui/background-beams.tsx
  src/components/ui/background-gradient.tsx
  src/components/ui/canvas-reveal-effect.tsx
  src/components/ui/timechart.tsx
  src/components/widgets/CategoryDisplay.tsx
  src/components/widgets/EventDisplay.tsx
  src/components/widgets/Timeline.tsx
  tailwind.config.ts
Labels: priority: high

#23 feat: some improvements in landing page
  package-lock.json
  package.json
  src/app/page.tsx
  src/app/scss/helpers.scss
  src/assets/cultural.png
  src/assets/mega.png
  src/assets/nontechnical.png
  src/assets/technical.png
  src/components/story/cylinder/cyllinder.module.scss
  src/components/story/cylinder/helpers.tsx
  src/components/story/cylinder/index.tsx
  src/components/story/intro/index.tsx
  src/components/story/intro/intro.module.scss
  src/components/story/last/index.tsx
  src/components/story/last/last.module.scss
  src/hooks/useViewport.tsx
Labels: priority: high

#36 feat: Add rulebook
  src/components/widgets/Header.tsx
Labels: priority: high, Blocked
